#!/usr/bin/env python

# Run this before you deploy it on replicate
import os
import sys
import torch
from diffusers import StableDiffusionPipeline, AutoencoderKL

# append project directory to path so predict.py can be imported
sys.path.append(".")
from predict import MODEL_NAME, MODEL_CACHE

# Make cache folders
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)

# Download SDXL-VAE-FP16-Fix
better_vae = AutoencoderKL.from_pretrained(
    "madebyollin/sdxl-vae-fp16-fix",
    torch_dtype=torch.float16,
)

# Download stablediffusionapi/juggernaut-xl
pipe = StableDiffusionPipeline.from_single_file(MODEL_NAME)
pipe.save_pretrained(MODEL_CACHE, safe_serialization=True)
